services:
  chest-backup:
    build: .
    network_mode: host
    volumes:
      - ./chest-backup.json:/app/chest-backup.json:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/hoarder/Backups/server:/mnt/hoarder/Backups/server:rw
      - /home/branko/Desktop/code/chest-backup/test/e2e:/backup-source/e2e:ro
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
